# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/traffic_db1}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres@123}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}
