# Database Configuration
spring.datasource.url=jdbc:postgresql://rushikesh:yilx03FjtE6ZXz5GlYs9lESxSTo4YBWh@dpg-d6se9stm5p6s73apavvg-a.singapore-postgres.render.com/traffic_db_8rp4
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres@123}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}
